// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CartQuantityController from "./cart_quantity_controller"
application.register("cart-quantity", CartQuantityController)

import CraftDetailsController from "./craft_details_controller"
application.register("craft-details", CraftDetailsController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SubtypeController from "./subtype_controller"
application.register("subtype", SubtypeController)

import SubtypeSortController from "./subtype_sort_controller"
application.register("subtype-sort", SubtypeSortController)

import VariantSelectorController from "./variant_selector_controller"
application.register("variant-selector", VariantSelectorController)
