// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SubtypeController from "./subtype_controller"
application.register("subtype", SubtypeController)

import SubtypeSortController from "./subtype_sort_controller"
application.register("subtype-sort", SubtypeSortController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)
