// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import SubtypeController from "./subtype_controller"
application.register("subtype", SubtypeController)
